use_frameworks!

target 'Euromsg_Example' do
  pod 'Euromsg', :path => '../'

  target 'Euromsg_Tests' do
    inherit! :search_paths

    
  end
end


target 'NotificationService' do
  pod 'Euromsg', :path => '../'
end

target 'NotificationContent' do
  pod 'Euromsg', :path => '../'
end