use_frameworks!

target 'Euromsg_Example' do
  
  pod 'Euromsg', :path => '../'

  target 'Euromsg_Tests' do
    inherit! :search_paths
  end
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'No'
    end
  end
end

target 'NotificationService' do
  use_frameworks!
  pod 'Euromsg', :path => '../'
end

target 'NotificationContent' do
  use_frameworks!
  pod 'Euromsg', :path => '../'
end