use_frameworks!

target 'Euromsg_Example' do
  pod 'Euromsg', :path => '../'
  target 'Euromsg_Tests' do
    inherit! :search_paths
  end
end


target 'NotificationService' do
  use_frameworks!
  pod 'Euromsg', :path => '../'
end

target 'NotificationContent' do
  use_frameworks!
  pod 'Euromsg', :path => '../'
end
